### ISSUE TITLE
Inquiry about Icon Style

### ISSUE THREAD

**Issue by Predidit** [MCDFsteve/FnipaPlay#1]
开发者您好，我对这个项目自述文件顶部的类似uwu风格的banner非常感兴趣。请问您是使用什么工具制作的呢。

**Comment by MCDFsteve** [comment]
<code>PhotoShop</code>。风格参考了[https://github.com/rakisaionji/SAWARATSUKI-ServiceLogos](https://github.com/rakisaionji/SAWARATSUKI-ServiceLogos)

**Comment by MCDFsteve** [comment]
我去，这不是canvas_danmaku插件的开发者吗，我这个播放器用了您做的这个来加载弹幕

**Comment by Predidit** [comment]
感谢您的回复。
